import Head from 'next/head'
import Image from 'next/image'
import Articles from '../components/mental-health/Articles'
import Footer from '../components/mental-health/Footer'
import Navbar from '../components/mental-health/Navbar'




export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
     </Head> 
     <Navbar />
     <Articles />
     <Footer />   </div>
  )
}
